#settings
DIR_PROJECT = /home/olivier/Projets/OpenLife
COMPILER = g++

CMD_COMPILATION = ${COMPILER} ${COMPILATION_FLAG}

CFL_STRICT = -Wall
CFL_SDL = -L/usr/X11R6/lib -lGL  -lGLU -lX11 -lSDL
CFL_THREAD = -lpthread

DIR_APP = ${DIR_PROJECT}/app
DIR_OBJ = ${DIR_APP}/resources
DIR_SRC = ${DIR_PROJECT}/src
DIR_TEST = ${DIR_PROJECT}/test

DIR_APP_TEST = ${DIR_TEST}
DIR_SRC_TEST = ${DIR_TEST}
