//
// Created by olivier on 21/08/2021.
//

#ifndef OPENLIFE_SERVER_DEFINITION_SERVICES_H
#define OPENLIFE_SERVER_DEFINITION_SERVICES_H

#define SRV_WORLDMAP 1;

#endif //OPENLIFE_SERVER_DEFINITION_SERVICES_H
